name: ms_ecommerce_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  ## cached storage
  shared_preferences: ^2.0.18
  ## state management
  provider: ^6.0.5
  ## switch button
  list_tile_switch: ^1.0.0
  ## ui
  flutter_staggered_grid_view: ^0.6.2
  badges: ^3.0.2
  # carousel_pro: ^1.0.0
  carousel_slider: ^4.2.1
  # flutter_swiper: ^1.1.6
  card_swiper: ^2.0.4
  backdrop: ^0.8.1
  carousel_pro_nullsafety: ^2.0.0
  smooth_page_indicator: ^1.0.1
  cloud_firestore: ^4.4.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_storage: ^11.0.16
  freezed_annotation: ^2.1.0
  # serializable
  json_annotation: ^4.6.0
  google_sign_in: ^6.0.2
  uuid: ^3.0.7
  wave: ^0.2.2
  http: ^0.13.5
  image_picker: ^0.8.7
  flutter_swiper_null_safety: ^1.0.2
  cached_network_image: ^3.2.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  build_runner: any  

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
